#!/usr/bin/sh

# this script is executed when the dell xps video adapter/dongle is connected
# xrandr / x doesnt automatically re apply configuration
# as no env variables are set, programs need an absolute path

# env >> /home/f1/logs/reconnect.log
notify-send "VIA-Labs video adapter connected"
/home/f1/dev/bin/x_monitor_switch -a
